"""Add description for character table

Revision ID: 099500603f74
Revises: 7a768b1cb052
Create Date: 2018-03-07 08:03:08.532420

"""

# revision identifiers, used by Alembic.
revision = '099500603f74'
down_revision = '7a768b1cb052'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('description', sa.Unicode(length=1024), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'description')
    # ### end Alembic commands ###
