"""Move og fields from oice to story

Revision ID: 09cf47b1c78c
Revises: 3d26dbfdf206
Create Date: 2017-05-26 13:06:02.947862

"""

# revision identifiers, used by Alembic.
revision = '09cf47b1c78c'
down_revision = '3d26dbfdf206'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import pyramid_safile

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oice', 'og_image')
    op.drop_column('oice', 'image')
    op.drop_column('oice', 'description')
    op.drop_column('oice', 'og_title')
    op.drop_column('oice', 'og_description')
    op.add_column('story', sa.Column('og_image', pyramid_safile.FileHandleStore(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'og_image')
    op.add_column('oice', sa.Column('og_description', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=False))
    op.add_column('oice', sa.Column('og_title', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=False))
    op.add_column('oice', sa.Column('description', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=False))
    op.add_column('oice', sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('oice', sa.Column('og_image', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
