"""Remove config and base.zip from project

Revision ID: 12da8bc7f96
Revises: 3d2e1021492
Create Date: 2016-11-09 12:51:58.366777

"""

# revision identifiers, used by Alembic.
revision = '12da8bc7f96'
down_revision = '30a75d1e735'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'config')
    op.drop_column('project', 'base_zip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('base_zip', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('project', sa.Column('config', mysql.TEXT(), nullable=False))
    ### end Alembic commands ###
