"""Add oice and story localization table

Revision ID: 1c48237a4838
Revises: 3f9a0c04e8eb
Create Date: 2017-05-31 11:48:31.296286

"""

# revision identifiers, used by Alembic.
revision = '1c48237a4838'
down_revision = '3f9a0c04e8eb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import pyramid_safile
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_localization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=1024), server_default='', nullable=False),
    sa.Column('description', sa.Unicode(length=4096), server_default='', nullable=False),
    sa.Column('language', sa.Unicode(length=5), server_default='zh-HK', nullable=False),
    sa.Column('cover_storage', pyramid_safile.FileHandleStore(length=255), nullable=True),
    sa.Column('og_image', pyramid_safile.FileHandleStore(length=255), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('storylocalization_oice_language_idx', 'story_localization', ['story_id', 'language'], unique=False)
    op.create_table('oice_localization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('oice_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Unicode(length=1024), server_default='', nullable=False),
    sa.Column('language', sa.Unicode(length=5), server_default='zh-HK', nullable=False),
    sa.ForeignKeyConstraint(['oice_id'], ['oice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('oicelocalization_oice_language_idx', 'oice_localization', ['oice_id', 'language'], unique=False)
    op.add_column('oice', sa.Column('language', sa.Unicode(length=5), server_default='zh-HK', nullable=False))
    op.drop_column('oice', 'og_locale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oice', sa.Column('og_locale', mysql.VARCHAR(length=5), server_default=sa.text("'zh_HK'"), nullable=False))
    op.drop_column('oice', 'language')
    op.drop_table('oice_localization')
    op.drop_table('story_localization')
    # ### end Alembic commands ###
