"""Update user read oice progress with time

Revision ID: 23a87850bb12
Revises: a7f1d46271f5
Create Date: 2017-07-04 05:16:10.938487

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '23a87850bb12'
down_revision = 'a7f1d46271f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_read_oice_progress', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_read_oice_progress', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_read_oice_progress', 'updated_at')
    op.drop_column('user_read_oice_progress', 'created_at')
    # ### end Alembic commands ###
