"""remove asset order default

Revision ID: 23d0adaf1ac
Revises: 125109a41d8
Create Date: 2016-12-22 10:38:43.095289

"""

# revision identifiers, used by Alembic.
revision = '23d0adaf1ac'
down_revision = '125109a41d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'order',
               existing_type=sa.Integer(),
               existing_nullable=False,
               server_default='0')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'order',
               existing_type=sa.Integer(),
               existing_nullable=False,
               server_default='999999')
    ### end Alembic commands ###
