"""add asset order

Revision ID: 26025843ec3
Revises: 532ea4108
Create Date: 2016-12-06 10:05:40.906906

"""

# revision identifiers, used by Alembic.
revision = '26025843ec3'
down_revision = '532ea4108'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('order', sa.Integer(), server_default='999999', nullable=False))
    conn = op.get_bind()
    res = conn.execute("SELECT id from library")
    results = res.fetchall()
    for library_id in results:
      conn.execute("""
         SET @count = 0;
         UPDATE asset SET
         asset.order = (@count := @count + 1)
         WHERE library_id = %d
         ORDER BY filename ASC;""" % (library_id[0]))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'order')
    ### end Alembic commands ###
