"""Add priority in library and story and view_count in oice

Revision ID: 2771aa716fa
Revises: 2bb56e39b4
Create Date: 2017-03-16 06:42:10.762783

"""

# revision identifiers, used by Alembic.
revision = '2771aa716fa'
down_revision = '2bb56e39b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('oice', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('story', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'priority')
    op.drop_column('oice', 'view_count')
    op.drop_column('library', 'priority')
    ### end Alembic commands ###
