"""Rename ks to oice

Revision ID: 282148eb767
Revises: 2a0b6af9f1c
Create Date: 2016-11-11 07:38:00.978784

"""

# revision identifiers, used by Alembic.
revision = '282148eb767'
down_revision = '2a0b6af9f1c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import pyramid_safile

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Unicode(length=1024), nullable=False, server_default=""),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default="0"),
    sa.Column('uuid', sa.Unicode(length=32), nullable=False, server_default=''),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('is_show_ad', sa.Boolean(), nullable=False, server_default="1"),
    sa.Column('og_description', sa.Unicode(length=1024), nullable=False, server_default=""),
    sa.Column('og_image', pyramid_safile.FileHandleStore(length=255), nullable=True),
    sa.Column('og_locale', sa.Unicode(length=5), server_default="zh_HK", nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    mysql_engine='InnoDB'
    )
    conn = op.get_bind()
    conn.execute("""
        INSERT oice SELECT * FROM ks""")

    op.drop_constraint('block_ibfk_1', 'block', type_='foreignkey')
    op.drop_constraint('project_export_ibfk_2', 'project_export', type_='foreignkey')
    op.drop_table('ks')
    op.create_foreign_key(None, 'project_export', 'oice', ['ks_id'], ['id'])
    op.add_column('block', sa.Column('oice_id', sa.Integer(), nullable=False))

    conn = op.get_bind()
    conn.execute("""
        UPDATE block SET oice_id = ks_id;""")

    op.create_foreign_key(None, 'block', 'oice', ['oice_id'], ['id'])
    op.drop_column('block', 'ks_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('ks_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'block', type_='foreignkey')
    op.create_foreign_key('block_ibfk_1', 'block', 'ks', ['ks_id'], ['id'])
    op.create_index('block_position_idx', 'block', ['position'], unique=False)
    op.create_index('block_id', 'block', ['id'], unique=False)
    op.drop_column('block', 'oice_id')
    op.create_table('ks',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('poll_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_show_ad', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('og_description', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=False),
    sa.Column('og_image', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('og_locale', mysql.VARCHAR(length=5), server_default=sa.text("'zh_HK'"), nullable=False),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('story_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], name='ks_ibfk_1'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name='ks_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('oice')
    ### end Alembic commands ###
