"""Asset Management Migration

Revision ID: 28e469539c5
Revises: c2a9ae9110
Create Date: 2016-12-01 10:06:46.568133

"""

# revision identifiers, used by Alembic.
revision = '28e469539c5'
down_revision = 'c2a9ae9110'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import pyramid_safile

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.alter_column('asset', 'name', new_column_name='name_en', existing_type=sa.Unicode(length=1024),
            existing_nullable=False)
    op.add_column('asset', sa.Column('name_jp', sa.Unicode(length=1024), nullable=False))
    op.add_column('asset', sa.Column('name_tw', sa.Unicode(length=1024), nullable=False))
    conn = op.get_bind()
    conn.execute("""
        UPDATE asset SET name_jp = name_en;
        UPDATE asset SET name_tw = name_en;""")
    op.add_column('character', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('library', sa.Column('cover_storage', pyramid_safile.FileHandleStore(length=255), nullable=True))
    op.add_column('library', sa.Column('description', sa.Unicode(length=4096), server_default='', nullable=False))
    op.add_column('library', sa.Column('is_public', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('library', sa.Column('license', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('story', sa.Column('cover_storage', pyramid_safile.FileHandleStore(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'cover_storage')
    op.drop_column('library', 'license')
    op.drop_column('library', 'is_public')
    op.drop_column('library', 'description')
    op.drop_column('library', 'cover_storage')
    op.drop_column('character', 'is_deleted')
    op.alter_column('asset', 'name_en', new_column_name='name', existing_type=sa.Unicode(length=1024),
            existing_server_default='', existing_nullable=False)
    op.drop_column('asset', 'name_tw')
    op.drop_column('asset', 'name_jp')
    op.drop_column('asset', 'is_deleted')
    ### end Alembic commands ###
