"""Add is_default in library

Revision ID: 2bb56e39b4
Revises: 2ee2e9b3851
Create Date: 2017-03-13 02:27:59.408087

"""

# revision identifiers, used by Alembic.
revision = '2bb56e39b4'
down_revision = '2ee2e9b3851'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'is_default')
    ### end Alembic commands ###
