"""Add index for tables

Revision ID: 2d106555cb25
Revises: 9804fcc0336f
Create Date: 2017-11-06 03:53:25.258230

"""

# revision identifiers, used by Alembic.
revision = '2d106555cb25'
down_revision = '9804fcc0336f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('library_id_deleted', table_name='asset')
    op.drop_index('library_id_deleted', table_name='character')
    op.create_index('asset_library_idx', 'asset', ['library_id', 'is_deleted'], unique=False)
    op.create_index('library_id_deleted_idx', 'character', ['library_id', 'is_deleted'], unique=False)
    op.create_index('characterid_assetid_idx', 'character_fgimages', ['character_id', 'asset_id'], unique=False)
    op.create_index('featuredlibrarylistlocalization_featuredlibrarylist_language_idx', 'featured_library_list_localization', ['list_id', 'language'], unique=False)
    op.create_index('ispublic_launchedat_idx', 'library', ['is_public', 'launched_at'], unique=False)
    op.create_index(op.f('ix_library_is_default'), 'library', ['is_default'], unique=False)
    op.create_index(op.f('ix_library_price'), 'library', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_price'), table_name='library')
    op.drop_index(op.f('ix_library_is_default'), table_name='library')
    op.drop_index('ispublic_launchedat_idx', table_name='library')
    op.drop_index('featuredlibrarylistlocalization_featuredlibrarylist_language_idx', table_name='featured_library_list_localization')
    op.drop_index('characterid_assetid_idx', table_name='character_fgimages')
    op.drop_index('library_id_deleted_idx', table_name='character')
    op.drop_index('asset_library_idx', table_name='asset')
    op.create_index('library_id_deleted', 'character', ['is_deleted', 'library_id'], unique=False)
    op.create_index('library_id_deleted', 'asset', ['is_deleted', 'library_id'], unique=False)
    # ### end Alembic commands ###
