"""Add facebook og fields for oice

Revision ID: 2ee2e9b3851
Revises: 37d6ea587a3
Create Date: 2017-02-22 07:58:20.695655

"""

# revision identifiers, used by Alembic.
revision = '2ee2e9b3851'
down_revision = '37d6ea587a3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import pyramid_safile


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oice', sa.Column('description', sa.Unicode(length=1024), server_default='', nullable=False))
    op.add_column('oice', sa.Column('image', pyramid_safile.FileHandleStore(length=255), nullable=True))
    op.add_column('oice', sa.Column('og_title', sa.Unicode(length=1024), server_default='', nullable=False))
    conn = op.get_bind()
    conn.execute("""
        UPDATE oice SET description = og_description;""")
    conn.execute("""
        UPDATE oice SET og_title = filename;""")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oice', 'og_title')
    op.drop_column('oice', 'image')
    op.drop_column('oice', 'description')
    ### end Alembic commands ###
