"""Add user link tables

Revision ID: 3001b770a993
Revises: 7d9db638a12f
Create Date: 2017-09-13 04:39:04.455143

"""

# revision identifiers, used by Alembic.
revision = '3001b770a993'
down_revision = '7d9db638a12f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_link_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('alias', sa.Unicode(length=32), nullable=False),
        sa.Column('name', sa.Unicode(length=1024), server_default='', nullable=False),
        sa.Column('link_regex', sa.Unicode(length=1024), server_default='', nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('alias', name='user_link_type_alias_unique')
    )
    op.create_table('user_link',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('user_link_type_id', sa.Integer(), nullable=True),
        sa.Column('label', sa.Unicode(length=1024), server_default='', nullable=False),
        sa.Column('link', sa.Text(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['user_link_type_id'], ['user_link_type.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_link_order_index', 'user_link', ['user_id', 'order'], unique=False)

    conn = op.get_bind()
    conn.execute('INSERT INTO user_link_type (alias, name, link_regex) VALUES'
                 '("facebook",      "Facebook",   "((http|https):\/\/)?((m|www)\.)?facebook.com\/"),'
                 '("twitter",       "Twitter",    "((http|https):\/\/)?((mobile|www)\.)?twitter.com\/"),'
                 '("pivix",         "Pivix",      "((http|https):\/\/)?((m|www)\.)?pixiv.net\/"),'
                 '("instagram",     "Instagram",  "((http|https):\/\/)?((www)\.)?instagram.com\/"),'
                 '("soundcloud",    "Soundcloud", "((http|https):\/\/)?soundcloud.com\/"),'
                 '("mirrorfiction", "鏡文學",      "((http|https):\/\/)?((www)\.)?mirrorfiction.com\/")'
                 )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_link_order_index', table_name='user_link')
    op.drop_table('user_link')
    op.drop_table('user_link_type')
    # ### end Alembic commands ###
