"""Add is_generic to character

Revision ID: 3398e6f11e51
Revises: 2771aa716fa
Create Date: 2017-03-27 04:15:59.033144

"""

# revision identifiers, used by Alembic.
revision = '3398e6f11e51'
down_revision = '2771aa716fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('is_generic', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'is_generic')
    # ### end Alembic commands ###
