"""Add fields in library table for LikeCoin support

Revision ID: 33dc391e517d
Revises: 099500603f74
Create Date: 2018-07-13 03:56:50.992755

"""

# revision identifiers, used by Alembic.
revision = '33dc391e517d'
down_revision = '099500603f74'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('discount_price', sa.Float(), server_default='0', nullable=False))
    op.add_column('library', sa.Column('settlement_currency', sa.Unicode(length=128), server_default='', nullable=True))
    op.create_index(op.f('ix_library_settlement_currency'), 'library', ['settlement_currency'], unique=False)

    # set paid libraries `settlement_currency` to fiat
    op.execute("""
        UPDATE `library`
        SET `settlement_currency` = 'fiat'
        WHERE `price` > 0
    """)

    # update official libraries `price`, and set `discount_price` at 8 LIKE
    op.execute("""
        UPDATE `library`
        SET
            `price` = 200,
            `discount_price` = 8,
            `settlement_currency` = 'likecoin'
        WHERE `id` IN (234, 454, 1377, 2163, 3449)
    """)
    # ### end Alembic commands ###


def downgrade():
    # revert official libraries as free
    op.execute("""
        UPDATE `library`
        SET
            `price` = 0
        WHERE `id` IN (234, 454, 1377, 2163, 3449)
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_settlement_currency'), table_name='library')
    op.drop_column('library', 'settlement_currency')
    op.drop_column('library', 'discount_price')
    # ### end Alembic commands ###
