"""Update sharing options

Revision ID: 36a76b07b0d6
Revises: 971e429b53d0
Create Date: 2017-04-18 09:52:02.577646

"""

# revision identifiers, used by Alembic.
revision = '36a76b07b0d6'
down_revision = '971e429b53d0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oice', 'sharing_option',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'999'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oice', 'sharing_option',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'999'"))
    # ### end Alembic commands ###
