"""Add tutorial_state

Revision ID: 37d6ea587a3
Revises: 364469432c0
Create Date: 2017-02-08 07:55:57.893287

"""

# revision identifiers, used by Alembic.
revision = '37d6ea587a3'
down_revision = '364469432c0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tutorial_state', mysql.BIT(length=32), server_default=sa.text("b'0'"), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tutorial_state')
    ### end Alembic commands ###
