"""Update user language value

Revision ID: 3d26dbfdf206
Revises: 746affed1875
Create Date: 2017-08-24 05:00:01.433269

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '3d26dbfdf206'
down_revision = '746affed1875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE `user` SET `language` = 'zh-HK' WHERE `language` = 'zh-Hant'")
    op.execute("UPDATE `user` SET `language` = 'ja' WHERE `language` = 'ja-JP'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE `user` SET `language` = 'zh-Hant' WHERE `language` = 'zh-HK'")
    op.execute("UPDATE `user` SET `language` = 'ja-JP' WHERE `language` = 'ja'")
    # ### end Alembic commands ###
