"""add subscription related column in user

Revision ID: 3d2e1021492
Revises: fb3d310fbd
Create Date: 2016-11-08 07:23:35.145886

"""

# revision identifiers, used by Alembic.
revision = '3d2e1021492'
down_revision = 'fb3d310fbd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', sa.Unicode(length=128), nullable=True, unique=True))
    op.add_column('user', sa.Column('expire_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'expire_date')
    op.drop_column('user', 'customer_id')
    ### end Alembic commands ###
