"""Update library related schema for asset store

Revision ID: 3e7379df50dd
Revises: 36a76b07b0d6
Create Date: 2017-04-18 10:46:47.262439

"""

# revision identifiers, used by Alembic.
revision = '3e7379df50dd'
down_revision = '36a76b07b0d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_tier',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('tier', sa.SmallInteger(), server_default='0', nullable=False),
        sa.Column('price_usd', sa.Float(), server_default='0', nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('featured_library',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('library_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), server_default='0', nullable=False),
        sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_purchased_library',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('library_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'library_id', name='user_id_library_id')
    )
    op.create_table('user_selected_library',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('library_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'library_id', name='user_id_library_id')
    )
    op.add_column('library', sa.Column('launched_at', sa.DateTime(), nullable=True))
    op.add_column('library', sa.Column('price', sa.Float(), server_default='-1', nullable=False))
    conn = op.get_bind()
    conn.execute("""UPDATE `library` SET `launched_at` = `created_at`, `price` = 0 WHERE `is_public` = true;""")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'price')
    op.drop_column('library', 'launched_at')
    op.drop_table('user_selected_library')
    op.drop_table('user_purchased_library')
    op.drop_table('featured_library')
    op.drop_table('price_tier')
    # ### end Alembic commands ###
