"""add localizable and language column in attribute

Revision ID: 3f9a0c04e8eb
Revises: 09cf47b1c78c
Create Date: 2017-05-29 09:13:21.920965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9a0c04e8eb'
down_revision = '09cf47b1c78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('language', sa.Unicode(length=5), nullable=True))
    op.add_column('attribute_definition',
                  sa.Column('localizable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    conn = op.get_bind()
    conn.execute("""
        UPDATE `story` SET `language` = REPLACE(`language`, '_', '-');""")
    where_clause = """
        WHERE
            `attribute_name` = 'text' OR
            `attribute_name` = 'answers' OR
            `attribute_name` = 'question' OR
            `attribute_name` = 'caption'  OR
            `attribute_name` = 'talk' OR
            `attribute_name` = 'dialog' OR
            `attribute_name` = 'name'"""
    conn.execute("""
        UPDATE `attribute_definition`
        SET `localizable` = true
        %s; """ % where_clause)
    conn.execute("""
        UPDATE `attribute`
        SET `language` = 'zh-HK'
        WHERE `attribute_definition_id` IN (
            SELECT `id`
            FROM `attribute_definition`
            %s
        ); """ % where_clause)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_definition', 'localizable')
    op.drop_column('attribute', 'language')
    # ### end Alembic commands ###
