"""Add column fork_of in story and oice

Revision ID: 41c94f4971e
Revises: 54043516d5d
Create Date: 2017-01-10 13:31:03.060737

"""

# revision identifiers, used by Alembic.
revision = '41c94f4971e'
down_revision = '54043516d5d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oice', sa.Column('fork_of', sa.Integer(), nullable=True))
    op.add_column('story', sa.Column('fork_of', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'fork_of')
    op.drop_column('oice', 'fork_of')
    ### end Alembic commands ###