"""Add username and ui_language fields in user

Revision ID: 4209860d3cef
Revises: 3001b770a993
Create Date: 2017-09-20 02:23:11.535705

"""

# revision identifiers, used by Alembic.
revision = '4209860d3cef'
down_revision = '3001b770a993'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ui_language', sa.Unicode(length=7), server_default='en', nullable=False))
    op.add_column('user', sa.Column('username', sa.Unicode(length=256), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])

    conn = op.get_bind()

    # try to set default username for existing user, and set ui_language according to language
    conn.execute("""
        UPDATE IGNORE `user`
        SET `username` = IF(
            LENGTH(SUBSTRING_INDEX(email, '@', 1)) > 6,
            SUBSTRING_INDEX(email, '@', 1),
            RPAD(SUBSTRING_INDEX(email, '@', 1), 6, '12345')
        )
        WHERE `email` LIKE '%%@%%'
        AND SUBSTRING_INDEX(email, '@', 1) NOT RLIKE '^[0-9]+$'
        AND LEFT(email, 1) RLIKE '[a-zA-Z]';

        UPDATE `user` SET `ui_language` = language
        WHERE LEFT(language, 2) = 'zh' OR language = 'ja';
    """)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_column('user', 'ui_language')
    # ### end Alembic commands ###
