"""after sync merge

Revision ID: 434f6152c11
Revises: 4a711c6a75d
Create Date: 2016-11-22 09:09:13.888562

"""

# revision identifiers, used by Alembic.
revision = '434f6152c11'
down_revision = '4a711c6a75d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ks_position_idx', table_name='block')
    op.create_index('ks_position_idx', 'block', ['oice_id', 'position'], unique=False)
    op.create_unique_constraint(None, 'character', ['library_id', 'key'])
    op.create_foreign_key(None, 'oice', 'poll', ['poll_id'], ['id'])
    op.create_foreign_key(None, 'oice', 'story', ['story_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oice', type_='foreignkey')
    op.drop_constraint(None, 'oice', type_='foreignkey')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_index('ks_position_idx', table_name='block')
    op.create_index('ks_position_idx', 'block', ['position'], unique=False)
    ### end Alembic commands ###
