"""Remove library_id in macro

Revision ID: 4a711c6a75d
Revises: 282148eb767
Create Date: 2016-11-11 11:31:46.103383

"""

# revision identifiers, used by Alembic.
revision = '4a711c6a75d'
down_revision = '282148eb767'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('macro_ibfk_1', 'macro', type_='foreignkey')
    op.drop_column('macro', 'library_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macro', sa.Column('library_id', mysql.INTEGER(display_width=11), nullable=False))
    op.create_foreign_key(None, 'macro', 'library', ['library_id'], ['id'])
    ### end Alembic commands ###
