"""add access_level for oice

Revision ID: 4f2d227f63c
Revises: 236744c1007
Create Date: 2016-12-01 14:41:38.562039

"""

# revision identifiers, used by Alembic.
revision = '4f2d227f63c'
down_revision = '236744c1007'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oice', sa.Column('access_level', sa.Integer(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oice', 'access_level')
    ### end Alembic commands ###
