"""Add credits url to asset

Revision ID: 4fe6c9548cfd
Revises: 8394248a2332
Create Date: 2017-07-20 08:55:45.667473

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4fe6c9548cfd'
down_revision = '8394248a2332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('credits_url', sa.Unicode(length=1024), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'credits_url')
    # ### end Alembic commands ###
