"""Remove poll and option

Revision ID: 501bbe9029f
Revises: 4b7c8549a10
Create Date: 2016-11-25 04:00:43.423945

"""

# revision identifiers, used by Alembic.
revision = '501bbe9029f'
down_revision = '4b7c8549a10'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    op.drop_table('option')
    op.drop_constraint('oice_ibfk_1', 'oice', type_='foreignkey')
    op.drop_table('poll')
    op.drop_column('oice', 'poll_id')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oice', sa.Column('poll_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('oice_ibfk_1', 'oice', 'poll', ['poll_id'], ['id'])
    op.create_table('poll',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('question', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('og_title', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('og_description', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('og_image_storage', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('option',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('poll_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], name='option_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
