"""Add tutorial_oice table

Revision ID: 54043516d5d
Revises: 67bf08dbad
Create Date: 2017-01-10 04:02:14.395655

"""

# revision identifiers, used by Alembic.
revision = '54043516d5d'
down_revision = '67bf08dbad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_oice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oice_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oice_id'], ['oice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

    conn = op.get_bind()
    conn.execute("""
        INSERT INTO tutorial_oice                        \
            (tutorial_oice.oice_id, tutorial_oice.order) \
        VALUES                                           \
            (872, 1),                                    \
            (649, 2),                                    \
            (651, 3),                                    \
            (697, 4),                                    \
            (699, 5),                                    \
            (701, 6),                                    \
            (702, 7),                                    \
            (703, 8);""")

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorial_oice')
    ### end Alembic commands ###
