"""Add language to featured_story

Revision ID: 5a75f1d14bfe
Revises: 7689849c5ede
Create Date: 2017-10-13 06:35:59.303705

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5a75f1d14bfe'
down_revision = '7689849c5ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured_story', sa.Column('language', sa.Unicode(length=5), server_default='zh-HK', nullable=False))
    op.add_column('featured_story', sa.Column('tier', sa.Integer(), nullable=False))

    op.create_index(op.f('ix_featured_story_language'), 'featured_story', ['language'], unique=False)
    op.create_index(op.f('ix_featured_story_order'), 'featured_story', ['order'], unique=False)
    op.create_index(op.f('ix_featured_story_tier'), 'featured_story', ['tier'], unique=False)
    op.create_index(op.f('ix_oice_is_deleted'), 'oice', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_oice_language'), 'oice', ['language'], unique=False)
    op.create_index('oice_ordering_idx', 'oice', ['id', 'order'], unique=False)
    op.create_index('oice_publicity_idx', 'oice', ['sharing_option', 'state'], unique=False)
    op.create_index(op.f('ix_story_is_deleted'), 'story', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_story_language'), 'story', ['language'], unique=False)
    op.create_index('story_updated_at_idx', 'story', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('story_updated_at_idx', table_name='story')
    op.drop_index(op.f('ix_story_language'), table_name='story')
    op.drop_index(op.f('ix_story_is_deleted'), table_name='story')
    op.drop_index('oice_publicity_idx', table_name='oice')
    op.drop_index('oice_ordering_idx', table_name='oice')
    op.drop_index(op.f('ix_oice_language'), table_name='oice')
    op.drop_index(op.f('ix_oice_is_deleted'), table_name='oice')
    op.drop_index(op.f('ix_featured_story_tier'), table_name='featured_story')
    op.drop_index(op.f('ix_featured_story_order'), table_name='featured_story')
    op.drop_index(op.f('ix_featured_story_language'), table_name='featured_story')

    op.drop_column('featured_story', 'tier')
    op.drop_column('featured_story', 'language')
    # ### end Alembic commands ###
