"""Add user read oice progress

Revision ID: 6635f10c7907
Revises: 7e4a61188eac
Create Date: 2017-06-22 09:06:25.135417

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6635f10c7907'
down_revision = '7e4a61188eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_read_oice_progress',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('oice_id', sa.Integer(), nullable=False),
        sa.Column('is_finished', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.ForeignKeyConstraint(['oice_id'], ['oice.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'oice_id', name='user_read_oice_unique'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_read_oice_progress')
    # ### end Alembic commands ###
