"""Add is_cancelled in user

Revision ID: 67bf08dbad
Revises: 448a0f79018
Create Date: 2016-12-28 07:56:02.866856

"""

# revision identifiers, used by Alembic.
revision = '67bf08dbad'
down_revision = '448a0f79018'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_cancelled', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_cancelled')
    ### end Alembic commands ###
