"""Add state in oice

Revision ID: 6fb55a4132fe
Revises: 3398e6f11e51
Create Date: 2017-04-03 07:22:14.964628

"""

# revision identifiers, used by Alembic.
revision = '6fb55a4132fe'
down_revision = '3398e6f11e51'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oice', sa.Column('state', sa.Integer(), server_default='0', nullable=False))
    conn = op.get_bind()
    conn.execute('UPDATE `oice` SET `state` = 2 WHERE `access_level` = 0;')
    op.alter_column('oice', 'access_level', new_column_name='sharing_option', server_default='999', existing_server_default='1', existing_type=sa.Integer)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oice', 'state')
    op.alter_column('oice', 'sharing_option', new_column_name='access_level', server_default='1', existing_server_default='999', existing_type=sa.Integer)
    # ### end Alembic commands ###
