"""Add like coin id to user

Revision ID: 7a768b1cb052
Revises: 8ba8945d1da0
Create Date: 2018-02-07 06:21:03.787359

"""

# revision identifiers, used by Alembic.
revision = '7a768b1cb052'
down_revision = '8ba8945d1da0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('like_coin_id', sa.Unicode(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['like_coin_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'like_coin_id')
    # ### end Alembic commands ###
