"""Add platform relate
d transaction column in user

Revision ID: 810fbe6bd66e
Revises: 364cb160b00d
Create Date: 2017-05-24 12:29:05.131956

"""

# revision identifiers, used by Alembic.
revision = '810fbe6bd66e'
down_revision = '364cb160b00d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('android_original_transaction_id', sa.Unicode(length=128), nullable=True))
    op.add_column('user', sa.Column('ios_original_transaction_id', sa.Unicode(length=128), nullable=True))
    op.add_column('user', sa.Column('platform', sa.Unicode(length=16), nullable=True))
    op.create_unique_constraint('uq_user_android_original_transaction_id', 'user', ['android_original_transaction_id'])
    op.create_unique_constraint('uq_user_ios_original_transaction_id', 'user', ['ios_original_transaction_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'platform')
    op.drop_column('user', 'ios_original_transaction_id')
    op.drop_column('user', 'android_original_transaction_id')
    # ### end Alembic commands ###
