"""Add title logo and hero image to story

Revision ID: 8394248a2332
Revises: 23a87850bb12
Create Date: 2017-07-14 04:31:30.679345

"""

from alembic import op
import sqlalchemy as sa
import pyramid_safile

# revision identifiers, used by Alembic.
revision = '8394248a2332'
down_revision = '23a87850bb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('hero_image', pyramid_safile.FileHandleStore(length=255), nullable=True))
    op.add_column('story', sa.Column('title_logo', pyramid_safile.FileHandleStore(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'title_logo')
    op.drop_column('story', 'hero_image')
    # ### end Alembic commands ###
