"""Add featured story

Revision ID: 86599aab5918
Revises: c3f2550e5759
Create Date: 2017-06-16 05:04:23.541505

"""

# revision identifiers, used by Alembic.
revision = '86599aab5918'
down_revision = 'c3f2550e5759'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'featured_story',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('story_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('featured_story')
    # ### end Alembic commands ###
