"""Add product id to user

Revision ID: 8ba8945d1da0
Revises: c507df5525d0
Create Date: 2018-01-18 04:10:07.364150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba8945d1da0'
down_revision = 'c507df5525d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('android_product_id', sa.Unicode(length=128), nullable=True))
    op.add_column('user', sa.Column('ios_product_id', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ios_product_id')
    op.drop_column('user', 'android_product_id')
    # ### end Alembic commands ###
