"""Add stripe connect fields

Revision ID: 8bfb33053381
Revises: 3e7379df50dd
Create Date: 2017-04-21 07:11:23.726854

"""

# revision identifiers, used by Alembic.
revision = '8bfb33053381'
down_revision = '3e7379df50dd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_access_token', sa.Unicode(length=128), nullable=True, unique=True))
    op.add_column('user', sa.Column('stripe_account_id', sa.Unicode(length=128), nullable=True, unique=True))
    op.add_column('user', sa.Column('stripe_refresh_token', sa.Unicode(length=128), nullable=True, unique=True))
    op.drop_column('price_tier', 'updated_at')
    op.drop_column('price_tier', 'created_at')
    conn = op.get_bind()
    conn.execute("""
        INSERT INTO price_tier (tier, price_usd) VALUES \
            (2, 2.99),                                   \
            (3, 3.99),                                   \
            (4, 4.99),                                   \
            (5, 5.99),                                   \
            (6, 6.99),                                   \
            (7, 7.99),                                   \
            (8, 8.99),                                   \
            (9, 9.99),                                   \
            (10, 14.99),                                   \
            (11, 19.99),                                   \
            (12, 24.99),                                   \
            (13, 29.99);""")
   # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_tier', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.add_column('price_tier', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.drop_column('user', 'stripe_refresh_token')
    op.drop_column('user', 'stripe_account_id')
    op.drop_column('user', 'stripe_access_token')
    # ### end Alembic commands ###
