"""Change default value of character order

Revision ID: 9b4fe51811
Revises: 23d0adaf1ac
Create Date: 2016-12-23 10:08:37.259502

"""

# revision identifiers, used by Alembic.
revision = '9b4fe51811'
down_revision = '23d0adaf1ac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'order',
               existing_type=sa.Integer(),
               existing_nullable=False,
               server_default='0')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'order',
               existing_type=sa.Integer(),
               existing_nullable=False,
               server_default=None)
    ### end Alembic commands ###
