"""Add seeking subscription message column in user

Revision ID: a7f1d46271f5
Revises: de9dc089bb7c
Create Date: 2017-06-29 09:06:30.984126

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a7f1d46271f5'
down_revision = 'de9dc089bb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('seeking_subscription_message', sa.Unicode(length=1024), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'seeking_subscription_message')
    # ### end Alembic commands ###
