"""Add likecoin_tx table

Revision ID: bbff7d7313c7
Revises: 33dc391e517d
Create Date: 2018-07-17 02:51:28.247853

"""

# revision identifiers, used by Alembic.
revision = 'bbff7d7313c7'
down_revision = '33dc391e517d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'likecoin_tx',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('product_type', sa.Unicode(length=128), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('tx_hash', sa.Unicode(length=128), nullable=True),
        sa.Column('from', sa.Unicode(length=128), nullable=True),
        sa.Column('to', sa.Unicode(length=128), nullable=True),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('max_reward', sa.Float(), server_default='0', nullable=False),
        sa.Column('status', sa.Unicode(length=128), server_default='pending', nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tx_hash'),
        sa.UniqueConstraint('user_id', 'product_type', 'product_id', name='user_id_product_type_product_id')
    )
    op.create_index(op.f('ix_likecoin_tx_product_type'), 'likecoin_tx', ['product_type'], unique=False)
    op.create_index(op.f('ix_likecoin_tx_status'), 'likecoin_tx', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likecoin_tx_status'), table_name='likecoin_tx')
    op.drop_index(op.f('ix_likecoin_tx_product_type'), table_name='likecoin_tx')
    op.drop_table('likecoin_tx')
    # ### end Alembic commands ###
