"""Add featured oice table

Revision ID: c2a9ae9110
Revises: 4f2d227f63c
Create Date: 2016-12-07 12:26:36.096771

"""

# revision identifiers, used by Alembic.
revision = 'c2a9ae9110'
down_revision = '4f2d227f63c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured_oice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oice_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oice_id'], ['oice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

    conn = op.get_bind()
    conn.execute("""
        INSERT INTO featured_oice                        \
            (featured_oice.oice_id, featured_oice.order) \
        VALUES                                           \
            (333,1),                                     \
            (682,2),                                     \
            (835,3);""")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('featured_oice')
    ### end Alembic commands ###
