"""Add localization table for character

Revision ID: cb62bebedb4d
Revises: 1c48237a4838
Create Date: 2017-06-02 09:39:25.985035

"""

# revision identifiers, used by Alembic.
revision = 'cb62bebedb4d'
down_revision = '1c48237a4838'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_localization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=1024), server_default='', nullable=False),
    sa.Column('language', sa.Unicode(length=5), server_default='zh-HK', nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('characterlocalization_character_language_idx', 'character_localization', ['character_id', 'language'], unique=False)
    op.alter_column('character', 'name_en', new_column_name='name', existing_type=sa.Unicode(length=1024), nullable=False)
    conn = op.get_bind()
    conn.execute("""
        INSERT INTO `character_localization` (character_id, name, created_at, updated_at) SELECT id, name_tw, created_at, updated_at FROM `character`;""")
    op.drop_column('character', 'name_tw')
    op.drop_column('character', 'name_jp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('name_jp', mysql.VARCHAR(length=1024), nullable=False))
    op.add_column('character', sa.Column('name_tw', mysql.VARCHAR(length=1024), nullable=False))
    op.alter_column('character', 'name', new_column_name='name_en', existing_type=sa.Unicode(length=1024), nullable=False)
    conn = op.get_bind()
    conn.execute("""
        UPDATE `character` SET `name_jp` = `name_en`, `name_tw` = `name_en` """)
    op.drop_table('character_localization')
    # ### end Alembic commands ###
