"""Add is_hidden field in asset table

Revision ID: d8737fd397e8
Revises: 4209860d3cef
Create Date: 2017-09-29 07:37:31.994903

"""

# revision identifiers, used by Alembic.
revision = 'd8737fd397e8'
down_revision = '4209860d3cef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'is_hidden')
    # ### end Alembic commands ###
